version: '2'
services:
    gestlr-app:
        image: gestlr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestlr-mysql:3306/gestlr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gestlr-mysql:
        extends:
            file: mysql.yml
            service: gestlr-mysql
